version: "3.9"

services:
  bot:
    build: .
    container_name: media-copy-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: media-bot-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
